Added FailedTestRemover tool.
winglam/dependent-tests-impact pull request #12
Opened 2017-10-07 01:06 UTC by ReedOei

2017-10-07 01:09 UTC, ReedOei commented
Tool does not comment out, just removes. I encountered a weird bug where it would add the comments to the object representing the file, but would not write them out to the file with the rest of the files content when running on the VM, but would work when on my own computer. 
I can try to fix it if it's an important feature.

2017-10-07 22:09 UTC, winglam requested changes

2017-10-07 22:09 UTC, winglam commented on dt-impact-tracer/src/edu/washington/cs/dt/impact/tools/FailedTestRemover.java
> +                    return false;
If the goal of this method is indeed to "remove the method declaration from all classes" then you should not return false here. You can use a boolean flag to keep track of whether you were successful in removing this method from at least one class and return the flag at the end of the method.

2017-10-07 22:09 UTC, winglam commented on dt-impact-tracer/src/edu/washington/cs/dt/impact/tools/FailedTestRemover.java
> +            System.out.println("Usage: java FailedTestRemover <classpath> <filename> [<output-dir>]");
Please expand the help message here with a description of what the class is meant to do, what the arguments are meant for and an example of using this class with one of our subjects.

2017-10-07 22:09 UTC, winglam commented on experiments/generate-sootTestOutput-auto.sh
> +# 7. Move auto tests to new subject/comment out those that don't compile
Please move step 7 to come after step 6 in this file.

2017-10-07 22:09 UTC, winglam commented on experiments/generate-sootTestOutput-auto.sh
> +# 7. Move auto tests to new subject/comment out those that don't compile
To fully complete step 7, we would have to copy the Randoop tests to the new subject, remove all the ones that do not compile, and finally generate a $NEW_DT_SUBJ/$SUBJ_NAME-auto-order file. This file will contain the list of Randoop tests that the new subject is actually compatible with and you can get that list by doing something similar to the existing step 4 of "Instructions to generate automatically-generated tests for a subject".

Your changes so far accomplish everything but generating a $NEW_DT_SUBJ/$SUBJ_NAME-auto-order file. Please amend your changes to this file to include this step.

2017-10-07 22:09 UTC, winglam commented on experiments/generate-sootTestOutput-auto.sh
> +# 7. Move auto tests to new subject/comment out those that don't compile
Once your changes to this file are complete, please take the relevant code segments from this file and update the Google sites guidelines for step 7 in "Instructions to generate automatically-generated tests for a subject" to reflect your awesome work to automate this step!

2017-10-07 22:09 UTC, winglam commented on dt-impact-tracer/src/edu/washington/cs/dt/impact/tools/FailedTestRemover.java
> +                    return false;
For each method that you end up removing, please record the fully qualified name of that method (https://stackoverflow.com/questions/11778032/fully-qualified-reference-to-java-method-signature) and save all such tests into a file called $SUBJ_NAME-auto-removed-tests in $NEW_DT_SUBJ.

2017-10-07 22:11 UTC, winglam commented
Commenting out the code instead of removing is not important. Please focus on fixing the issues mentioned above instead.

2017-10-09 21:02 UTC, ReedOei commented
I have made the changes you requested.

2017-10-09 21:14 UTC, winglam commented
LGTM! The change for the tool to accept multiple files is appreciated.

2017-10-09 21:14 UTC, merged